language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.gradle'
#    - '$HOME/.m2/repository' #필요없음 maven 관련해서 필요한 캐싱임.

before_install:
  - chmod +x gradlew

script: "ll"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - lkorea12345@gmail.com