version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/springboot-aws-practice
    overwrite: yes

# CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 합니다.
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user