# logging-deploy.yml

name: logging-system

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout from Github to this->repo
        uses: actions/checkout@v2
      
      - name: Set up JDK 1.8 (Java 8)
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
        
      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash
