# main.yml

name: file(.jar) upload to S3 and trigger CodeDeploy to deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  S3_BUCKET_NAME: springboot-aws-practice-s3
  PROJECT_NAME: springboot-aws-practice

jobs:
  build:
    environment: AWS_S3_CODEDEPLOY_KEY
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout from Github to this->repo
        uses: actions/checkout@v2
      
      - name: Set up JDK 1.8 (Java SE 8)
        uses: actions/setup-java@v2
        with:
          java-version: 8 # Specify java version *not* JDK internal version
          distribution: 'zulu'
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
        
      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash
        
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip . # 현재 폴더에 $GITHUB_SHA라는 값으로 압축파일을 만들고, 현재 폴더를 전부 압축함
        shell: bash
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Upload to s3
        run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name springboot-aws-practice --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name springboot-aws-practice-group --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
      
