# main.yml

name: file(.jar) upload to S3 and trigger CodeDeploy to deploy

on:
  workflow_dispatch:

env:
  S3_BUCKET_NAME: springboot-aws-practice-s3
  PROJECT_NAME: springboot-aws-practice

jobs:
  build:
    env:
      key1: ${{ secrets.AWS_ACCESS_KEY_ID }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Test for secret env
        if: ${{ env.key1 }} == 'del'
        run: echo "repo"
        shell: bash
  
