# main.yml

name: file(.jar) upload to S3 and trigger CodeDeploy to deploy

on:
  workflow_dispatch:

env:
  S3_BUCKET_NAME: springboot-aws-practice-s3
  PROJECT_NAME: springboot-aws-practice

jobs:
  build:
    env:
      key1: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Test for secret env
        if: ${{'DEP' == 'del'}}
        run: echo "repo"
        shell: bash
        
      - name: Test for secret env else
        if: ${{'DEP' != 'del'}}
        run: echo "env"
        shell: bash
