# main.yml

name: file(.jar) upload to S3 and trigger CodeDeploy to deploy

on:
  workflow_dispatch:

env:
  S3_BUCKET_NAME: springboot-aws-practice-s3
  PROJECT_NAME: springboot-aws-practice

jobs:
  build:
    environment: AWS_S3_CODEDEPLOY_KEY
    env:
      key1: ${{ secrets.AWS_ACCESS_KEY_ID }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Test for IF
        if: ${{'DEP' == 'del'}}
        run: echo "if"
        shell: bash
        
      - name: Test for ELSE
        if: ${{'DEP' != 'del'}}
        run: echo "else"
        shell: bash

      - name: Test for secret env IF
        if: ${{env.key1 == 'dep'}}
        run: echo "repo"
        shell: bash
      
      - name: Test for secret env ELSE
        if: ${{env.key1 != 'dep'}}
        run: echo "env"
        shell: bash
