# main.yml

name: file(.jar) upload to S3 and trigger CodeDeploy to deploy

on:
  workflow_dispatch:

env:
  S3_BUCKET_NAME: springboot-aws-practice-s3
  PROJECT_NAME: springboot-aws-practice

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test for secret env
      - if: ${{ secrets.AWS_ACCESS_KEY_ID  }} == 'dep'
        run: echo "repo"
        shell: bash
  
